const translations = {
  en: { navWorkflow:"Workflow", navFeatures:"Features", navPrivacy:"Privacy", download:"Download", eyebrow:"Native macOS · Private by default", heroTitle:"Make the whole video<br />visible at once.", heroSummary:"ShotTessera turns video into clean, configurable contact sheets—locally, quickly, and without a complicated editing suite.", heroDownload:"Download for macOS", viewSource:"View source <span aria-hidden=\"true\">↗</span>", compatibility:"macOS 13+ · Apple Silicon & Intel · Free and open source", queue:"Queue", preview:"Contact sheet", settings:"Settings", grid:"Grid", background:"Background", format:"Format", workflowEyebrow:"A focused workflow", workflowTitle:"From video to contact sheet in three steps.", stepOneTitle:"Drop in your videos", stepOneText:"Add one clip or a batch. The queue stays simple and visible.", stepTwoTitle:"Choose the moments", stepTwoText:"Use intelligent selection, then fine-tune with a real player timeline when you need control.", stepThreeTitle:"Export the story", stepThreeText:"Set grid, dimensions, background, labels, and PNG or JPG—then save beside your video.", featuresEyebrow:"Designed for the edit, not the setup", featuresTitle:"The useful frame, without the noise.", featuresSummary:"Every part of ShotTessera is tuned for the moment you need to review a film, share a scene, or find a shot again.", featureOneTitle:"Smarter frame selection", featureOneText:"Balances sharpness, scene variety, faces, action, and text-heavy screens for more useful results.", featureTwoTitle:"Manual precision", featureTwoText:"Scrub a visual timeline, step by frames, type a timecode, and number your selected sequence.", featureThreeTitle:"Made for your format", featureThreeText:"From 3 × 3 to 8 × 8, landscape to vertical, with backgrounds that match the material.", privacyEyebrow:"Your footage stays yours", privacyTitle:"No account. No upload. No cloud queue.", privacyText:"Frame analysis and export happen on your Mac. ShotTessera has no telemetry, cloud processing, Electron, FFmpeg, or Python runtime.", ctaEyebrow:"A clearer way to review video", ctaTitle:"Start with the whole picture.", github:"GitHub", feedback:"Feedback" },
  zh: { navWorkflow:"工作流", navFeatures:"功能", navPrivacy:"隐私", download:"下载", eyebrow:"原生 macOS · 默认保护隐私", heroTitle:"让整部影片，<br />一眼可见。", heroSummary:"ShotTessera 在本机快速制作干净、可自定义的影片拼图，不必打开复杂的剪辑软件。", heroDownload:"下载 macOS 版", viewSource:"查看源码 <span aria-hidden=\"true\">↗</span>", compatibility:"macOS 13+ · Apple Silicon 与 Intel · 免费开源", queue:"视频队列", preview:"分镜预览", settings:"分镜设置", grid:"网格", background:"底色", format:"格式", workflowEyebrow:"专注的工作流", workflowTitle:"三步，把影片变成分镜拼图。", stepOneTitle:"加入影片", stepOneText:"单部或批量添加，清晰的队列始终可见。", stepTwoTitle:"挑选关键画面", stepTwoText:"先用智能选帧，再通过真实播放器时间轴细调到需要的位置。", stepThreeTitle:"导出故事", stepThreeText:"设定网格、尺寸、底色、标签和 PNG/JPG，然后保存到影片旁。", featuresEyebrow:"专为看片，而非复杂设置", featuresTitle:"留下有用画面，过滤无用干扰。", featuresSummary:"ShotTessera 的每一处设计，都服务于审片、分享场景和再次找到某个镜头的时刻。", featureOneTitle:"更聪明的选帧", featureOneText:"综合清晰度、镜头变化、人物、动作与文字密度，挑出更有用的画面。", featureTwoTitle:"手动精确控制", featureTwoText:"可滑动视觉时间轴、逐帧微调、输入时间码，并为选中画面标记顺序。", featureThreeTitle:"适合你的画幅", featureThreeText:"支持 3 × 3 至 8 × 8，以及横屏、竖屏和多种适配底色。", privacyEyebrow:"你的影片，只属于你", privacyTitle:"无需账号，不上传，没有云端队列。", privacyText:"画面分析与导出都在你的 Mac 上完成。ShotTessera 没有遥测、云处理、Electron、FFmpeg 或 Python 运行时。", ctaEyebrow:"更清晰地审看影片", ctaTitle:"从全局，看见故事。", github:"GitHub", feedback:"反馈" },
  ja: { navWorkflow:"ワークフロー", navFeatures:"機能", navPrivacy:"プライバシー", download:"ダウンロード", eyebrow:"ネイティブ macOS · プライバシーを標準に", heroTitle:"動画全体を、<br />一目で把握。", heroSummary:"ShotTessera は複雑な編集ソフトを使わず、動画から整ったコンタクトシートを Mac 上で素早く作成します。", heroDownload:"macOS 版をダウンロード", viewSource:"ソースを見る <span aria-hidden=\"true\">↗</span>", compatibility:"macOS 13+ · Apple Silicon / Intel · 無料・オープンソース", queue:"キュー", preview:"コンタクトシート", settings:"設定", grid:"グリッド", background:"背景", format:"形式", workflowEyebrow:"集中できるワークフロー", workflowTitle:"3 ステップで動画をコンタクトシートに。", stepOneTitle:"動画を追加", stepOneText:"1 本でもバッチでも追加。キューは常にシンプルで見やすく保たれます。", stepTwoTitle:"瞬間を選ぶ", stepTwoText:"スマート選択の後、実際のプレイヤーのタイムラインで必要なフレームまで追い込めます。", stepThreeTitle:"ストーリーを書き出す", stepThreeText:"グリッド、サイズ、背景、表示、PNG/JPG を選び、動画の隣に保存します。", featuresEyebrow:"設定より、映像を見るために", featuresTitle:"必要なフレームだけを、ノイズなく。", featuresSummary:"ShotTessera は作品の確認、シーンの共有、必要なカットの再発見のために設計されています。", featureOneTitle:"より賢いフレーム選択", featureOneText:"鮮明さ、場面の変化、人物、アクション、文字量をバランスよく評価します。", featureTwoTitle:"手動での精密操作", featureTwoText:"視覚タイムラインのスクラブ、フレーム単位の調整、タイムコード入力、選択順の番号付けに対応。", featureThreeTitle:"多彩なフォーマット", featureThreeText:"3 × 3 から 8 × 8、横長から縦長、素材に合わせた背景色まで対応します。", privacyEyebrow:"あなたの映像は、あなたのもの", privacyTitle:"アカウント不要。アップロード不要。クラウド処理不要。", privacyText:"フレーム解析と書き出しはすべて Mac 内で行われます。ShotTessera はテレメトリー、クラウド処理、Electron、FFmpeg、Python ランタイムを使用しません。", ctaEyebrow:"動画をもっと明快に確認", ctaTitle:"全体像から、物語を読む。", github:"GitHub", feedback:"フィードバック" }
};
function activateLanguage(language) {
  document.documentElement.lang = language === "zh" ? "zh-CN" : language;
  document.querySelectorAll("[data-i18n]").forEach((node) => { node.innerHTML = translations[language][node.dataset.i18n]; });
  document.querySelectorAll("[data-lang]").forEach((button) => button.setAttribute("aria-pressed", String(button.dataset.lang === language)));
  localStorage.setItem("shottessera-language", language);
}
document.querySelectorAll("[data-lang]").forEach((button) => button.addEventListener("click", () => activateLanguage(button.dataset.lang)));
activateLanguage(localStorage.getItem("shottessera-language") || "en");
